### ISSUE TITLE
Successfully run leaflet imaging example

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/dat_pyinthesky#13]
https://github.com/spacetelescope/dat_pyinthesky/blob/master/jupyter_platform/html_view_into_leaflet.ipynb
This could be in either jupyterlab or jupyter notebook

Jira issue: https://jira.stsci.edu/browse/DATJPP-5

- [x] Lim -- works in `notebook`, does not work in `lab` (same problem as what Harry reported in https://github.com/spacetelescope/dat_pyinthesky/issues/13#issuecomment-480047449)
- [x] Busko
- [x] Earl
- [x] Ogaz
- [x] Averbukh
- [x] Geda
- [x] Jones
- [ ] Robitaille
- [x] Harry (notebook okay; having trouble in jupyterlab)

**Comment by ibusko** [comment]
Importing ipyleaflet causes an error within the notebook, even though I can import it successfully from the python commnand interpreter level:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/busko/Projects/miniconda3_mosviz/envs/jupyter/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/busko/Projects/miniconda3_mosviz/envs/jupyter/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-5-602be9eb76da>", line 1, in <lambda>
    th = threading.Thread(target=lambda:app.run(debug=False, use_reloader=False, port=5013))
  File "/Users/busko/Projects/miniconda3_mosviz/envs/jupyter/lib/python3.6/site-packages/flask/app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "/Users/busko/Projects/miniconda3_mosviz/envs/jupyter/lib/python3.6/site-packages/flask/cli.py", line 629, in show_server_banner
    click.echo(message)
  File "/Users/busko/Projects/miniconda3_mosviz/envs/jupyter/lib/python3.6/site-packages/click/utils.py", line 259, in echo
    file.write(message)
io.UnsupportedOperation: not writable

The script keeps running down to where it tries to load a non-existent file (tmp/jclj01tvq_flc.fits).

**Comment by robelgeda** [comment]
Got the same error

**Comment by SaOgaz** [comment]
@ibusko, i was able to replace that file with a fits file i had on hand and it worked fine. Robel was able to do the same.

**Comment by hcferguson** [comment]
Works for me in a notebook. Also tried it on a CANDELS image and that worked.

**Comment by hcferguson** [comment]
Tried it in jupyter lab and got an error on importing astroquery, even though it should be using the same conda environment as the notebook:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b3be6a367f5b> in <module>
     17 import ipywidgets
     18 
---> 19 from astroquery import mast
     20 
     21 from IPython import display

ModuleNotFoundError: No module named 'astroquery'
```

**Comment by hcferguson** [comment]
Re-installed jupyterlab and got past the astroquery problem. Now it runs in the notebook but I don't get the leaflet viewer in jupyterlab. Getting a partial error message:
``` Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map …```

**Comment by pllim** [comment]
```
CCDData.read(default_file_name)
```
does not work on Windows. Get
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\...\\AppData\\Local\\Temp\\tmp641sbx5x'
```

**Comment by pllim** [comment]
Is the repeated tiling intentional? Is that a feature or a bug? I find the repeat very confusing.

![leaflet_tiles](https://user-images.githubusercontent.com/2090236/55670206-ab3be280-584f-11e9-8f93-e6aa21ebb3af.jpg)

**Comment by astrofrog** [comment]
Sorry for the delay - I'm having issues with getting the data via astroquery:

```
obses = mast.Observations.query_region('M32', radius=30*u.arcsec)

acsm32 = obses[(obses['instrument_name']=='ACS/WFC')&(obses['filters']=='F555W')&(obses['obs_collection']=='HST')]
acsm32 = acsm32[np.argmax(acsm32['t_exptime'])]
acsm32
```

returns

```
---------------------------------------------------------------------------
RemoteServiceError                        Traceback (most recent call last)
<ipython-input-4-a3c86bf5a0ce> in <module>
----> 1 obses = mast.Observations.query_region('M32', radius=30*u.arcsec)
      2 
      3 acsm32 = obses[(obses['instrument_name']=='ACS/WFC')&(obses['filters']=='F555W')&(obses['obs_collection']=='HST')]
      4 acsm32 = acsm32[np.argmax(acsm32['t_exptime'])]
      5 acsm32

~/python/dev/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

~/python/dev/lib/python3.7/site-packages/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response
---> 29             result = self._parse_result(response, verbose=verbose)
     30             self.table = result
     31             return result

~/python/dev/lib/python3.7/site-packages/astroquery/mast/core.py in _parse_result(self, responses, verbose)
    545             # check for error message
    546             if result['status'] == "ERROR":
--> 547                 raise RemoteServiceError(result.get('msg', "There was an error with your request."))
    548 
    549             resTable = _mashup_json_to_table(result, colConfig)

RemoteServiceError: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
```

Has anyone else seen this? (this is a server-side error by the way, not client-side such as e.g. local timeot)
