### ISSUE TITLE
Succesfully run voilable astrowidget notebook

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/dat_pyinthesky#14]
https://github.com/spacetelescope/dat_pyinthesky/blob/master/jupyter_platform/voilable_astrowidgets.ipynb
This could be in either jupyterlab or jupyter notebook

Jira issue: https://jira.stsci.edu/browse/DATJPP-3

- [x] Lim -- No problem with `voilable_astrowidgets.ipynb` on Windows both on notebook and lab.
- [x] Busko
- [x] Earl
- [x] Ogaz
- [x] Averbukh
- [x] Geda
- [x] Jones
- [x] Robitaille
- [x] Ferguson

**Comment by ibusko** [comment]
This works for me. It raises a warning about installing opencv, but works regardless.

**Comment by pllim** [comment]
`opencv` is indeed optional and only speed things up in Ginga for certain array operations. You can ignore the warning if you don't care about optimal performance.

**Comment by hcferguson** [comment]
works for me.

**Comment by astrofrog** [comment]
Works for me in the notebook and running voila subsequently also works
