### ISSUE TITLE
CI Bugs

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/dat_pyinthesky#140]
- [x] [Ifu Cube Continuum Fit - Requirements install issue ( dependency conflict )](https://app.circleci.com/pipelines/github/jbcurtin/dat_pyinthesky/35/workflows/febd0e19-8256-4e42-a8b3-db174fab2336/jobs/282)
- [ ] [Niriss Ami Binary - Requirements install issue ( numpy )](https://app.circleci.com/pipelines/github/jbcurtin/dat_pyinthesky/35/workflows/febd0e19-8256-4e42-a8b3-db174fab2336/jobs/284)
    - [ ] oifits/oifits.py
    - [ ] PR
- [ ] Preimaging Error
    - [x] min max

**Comment by jbcurtin** [comment]
Build Errors Notebook Leads should look into
* https://app.circleci.com/pipelines/github/spacetelescope/dat_pyinthesky/475/workflows/f478c21d-dd71-4c31-ad1f-deae919860d4/jobs/1333
