### ISSUE TITLE
Successfully run voilable astrowidget in voila

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/dat_pyinthesky#15]
https://github.com/spacetelescope/dat_pyinthesky/blob/master/jupyter_platform/voilable_astrowidgets.ipynb

Note that for this issue, you should also try to execute that via the “astrowidgets_viewer” script, which uses voila (https://github.com/QuantStack/voila). DATJPP-3 is the same notebook, but to get it working in the notebook/jupyterlab

Jira issue: https://jira.stsci.edu/browse/DATJPP-2

- [x] Lim: Tried on Windows 10 and failed. See #16, d30fc0e, QuantStack/voila#98, QuantStack/voila#99, and QuantStack/voila#100. But then got it to work after #18, but still has a bug reported in #19.
- [x]  Busko 
- [x] Earl
- [x]  Ogaz
- [x]  Averbukh
- [x] Geda
- [x]  Jones
- [x]  Robitaille
- [x] Ferguson

**Comment by ibusko** [comment]
Looks like it's running correctly, but it reports this in the terminal window:

(jupyter) anakin:/Users/busko $ astrowidgets_viewer
VOILA: 56611
[Voila] Using /var/folders/f2/dsq1cxxd78n9vltk6_6kwxtr0000zf/T to store connection files
[Voila] Storing connection files in /var/folders/f2/dsq1cxxd78n9vltk6_6kwxtr0000zf/T/voila_dfsq0mbb.
[Voila] Serving static files from /Users/busko/Projects/miniconda3_mosviz/envs/jupyter/lib/python3.6/site-packages/voila/static.
[Voila] Voila listening on port 8866.
AVDCreateGPUAccelerator: Error loading GPU renderer
[Voila] Kernel started: 06ca9572-0d3e-4979-8472-5b787d62390f
2019-04-04 14:10:37.349 Google Chrome[56615:4506735] Errors logged by ksadmin: KSKeyedPersistentStore store directory does not exist. [com.google.UpdateEngine.CommonErrorDomain:501 - '/Library/Google/GoogleSoftwareUpdate/TicketStore' - 'KSKeyedPersistentStore.m:327']
KSPersistentTicketStore failed to load tickets. (productID: com.google.Chrome) [com.google.UpdateEngine.CoreErrorDomain:1051 - '/Library/Google/GoogleSoftwareUpdate/TicketStore/Keystone.ticketstore'] (KSKeyedPersistentStore store directory does not exist. - '/Library/Google/GoogleSoftwareUpdate/TicketStore' [com.google.UpdateEngine.CommonErrorDomain:501])
ksadmin cannot access the ticket store:<KSUpdateError:0x7ff708f086e0
	domain="com.google.UpdateEngine.CoreErrorDomain"
	code=1051
	userInfo={
		function = "-[KSProductKeyedStore(ProtectedMethods) errorForStoreError:productID:message:timeoutMessage:]";
		date = 2019-04-04 18:10:37 +0000;
		productids = {(
			"com.google.Chrome"
		)};
		filename = "KSProductKeyedStore.m";
		line = 102;
		NSFilePath = "/Library/Google/GoogleSoftwareUpdate/TicketStore/Keystone.ticketstore";
		NSUnderlyingError = <KSError:0x7ff708f05790
			domain="com.google.UpdateEngine.CommonErrorDomain"
			code=501
			userInfo={
				NSLocalizedDescription = "KSKeyedPersistentStore store directory does not exist.";
				line = 327;
				filename = "KSKeyedPersistentStore.m";
				function = "-[KSKeyedPersistentStore(PrivateMethods) validateStorePath]";
				NSFilePath = "/Library/Google/GoogleSoftwareUpdate/TicketStore";
				date = 2019-04-04 18:10:37 +0000;
			}
		>;
		NSLocalizedDescription = "KSPersistentTicketStore failed to load tickets.";
	}
>
[Voila] Executing notebook with kernel: 
WARNING:tornado.access:404 GET /favicon.ico (::1) 0.54ms
[Voila] Adapting to protocol v5.1 for kernel 06ca9572-0d3e-4979-8472-5b787d62390f

**Comment by hcferguson** [comment]
Got it to work after downgrading to tornado v5.1.1.

**Comment by astrofrog** [comment]
Works for me
