### ISSUE TITLE
Test cubeviz base functionality in plotly + ipywidgets

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/dat_pyinthesky#25]
From [functional spec](https://innerspace.stsci.edu/display/DSMO/Elaboration%3A+Cubeviz-in-browser+prototype?focusedCommentId=162048038#comment-162048038), do 1-3 using  plotly + ipywidgets. Stetch goal to achieve 4 (displaying in an ipywidgets text box but with cursor information from plotly).

Wording of tasks (1-3) may be re-done in the near future, so keep that in mind.  Please feel free to post any and all implementation questions here in the issue!  This will be the best recorded forum to get any details worked out that might come up.

JIRA product board ticket: https://jira.stsci.edu/browse/DATJPP-15

**Comment by brechmos-stsci** [comment]
Some notes on the whole thing:
- Plotly was reasonably easy to use for display and interacting. I had some questions and the forums were very helpful. The documentation was decent, generally.
- There were issues with widgets not showing up in Jupyter Lab so the notebook will only work in Jupyter Notebooks
- All the widgets I needed were available
- There will be a little question about how to do regions but overlaying a scatter plot on an image seems to be the suggested way to do it (based on a post in the forums and a webpage)
