### ISSUE TITLE
Test cubeviz base functionality in bokeh + ipywidgets

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/dat_pyinthesky#26]
From [functional spec](https://innerspace.stsci.edu/display/DSMO/Elaboration%3A+Cubeviz-in-browser+prototype?focusedCommentId=162048038#comment-162048038), do 1-3 using  bokeh + ipywidgets. Stetch goal to achieve 4 (displaying in an ipywidgets text box but with cursor information from bokeh).

Wording of tasks (1-3) may be re-done in the near future, so keep that in mind.  Please feel free to post any and all implementation questions here in the issue!  This will be the best recorded forum to get any details worked out that might come up.

JIRA product board ticket: https://jira.stsci.edu/browse/DATJPP-16

**Comment by pllim** [comment]
https://github.com/spacetelescope/dat_pyinthesky/issues/49#issuecomment-486434467

**Comment by robelgeda** [comment]
The ipywidget slider calls the bokeh redraw function too often which leads to a major lag. Given the poor interaction between the two tools, we have decided to not use them in combination for future development. It was also noted that there may be a way around the but it will most likely require us to hack the bokeh redraw function to blit the image onto the plot.
