### ISSUE TITLE
Run #26 Notebook in voila

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/dat_pyinthesky#49]
#26 

Jira Issue:
https://jira.stsci.edu/browse/DATJPP-8

**Comment by pllim** [comment]
I don't think this is possible as I can't find any notebook by @robelgeda that addresses #26 . There is nothing to run `voila` on for this.

**Comment by robelgeda** [comment]
Sorry about that, i can confirm it is not possible because we decided the combination of tools doesn't work well and that we will not be using them.

**Comment by robelgeda** [comment]
I commented on #26 also
