### ISSUE TITLE
Run #25 in Voila

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/dat_pyinthesky#50]
#25 

Jira Issue:
https://jira.stsci.edu/browse/DATJPP-8

**Comment by obviousrebel** [comment]
I'll take a try at this, I currently don't have permissions to assign myself though.

**Comment by obviousrebel** [comment]
When using voila, widgets are loading but it seems the actual image viewer isn't. Cause is unknown.

**Comment by pllim** [comment]
Any traceback on the terminal?

**Comment by obviousrebel** [comment]
I wish but there are no errors or traceback. The plot just doesn't appear.

**Comment by pllim** [comment]
I can't even run that notebook without voila. See brechmos-stsci/vizapp#5

**Comment by obviousrebel** [comment]
I had issues as well but I got it to work by cloning https://github.com/brechmos-stsci/vizapp and then specifying the path in the import statements at the top of the notebook. I also had to change some import names.
```
import sys
sys.path.append('PATH_TO_CLONED_REPO/vizapp/vizapp')

from vizapp import VizApp
from viewers.viewer1d import Viewer1D
from viewers.viewernd import PlotlyViewerND
```

**Comment by pllim** [comment]
I try not to mess up my PATH if I can...

**Comment by pllim** [comment]
@obviousrebel , did you try running the notebook outside `voila` first as a normal notebook? I found that we actually need the `viewerND` branch of `vizapp`. See #59.
